name: J-Chess Docker Build and Push

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: j-chess-server
  REPO_NAME: ${{ github.actor }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Create image name
      id: CIN
      run: echo ::set-output name=image_name::$(echo ${REPO_NAME}/${IMAGE_NAME} | tr '[:upper:]' '[:lower:]')
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: ${{ steps.CIN.outputs.image_name }}
        # Tags override for Docker image
        # tags: # optional
        # Target Docker registry
        registry: ${{ env.REGISTRY }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Directory to run `docker build` from, if not project root
        directory: . # optional
        # Docker build arguments passed via --build-arg
        # buildArgs: # optional
        # Docker build labels passed via --label
        # labels: # optional
        # Docker build target passed via --target
        # target: # optional
        # Docker registry username
        # username: # optional
        # Docker registry password
        # password: # optional
        # GitHub organization to push image to (if not current)
        # gitHubOrg: # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: true # optional, default is false
        # Suffixes a build timestamp to the branch-based Docker tag
        addTimestamp: true # optional, default is false
